pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  flags: "-docker -use_docker_cache -timeout=8m -print-log"
  shards: [0, 1, 2, 3, 4]
  flavors: ["mysql56", "mysql57", "mysql80", "mariadb", "mariadb103", "percona57", "percona80"]
jobs:
- job: tests
  strategy:
    matrix:
      ${{ each flavor in variables.flavors }}:
        ${{ each shard in variables.shards }}:
         ${{ format('{0}{1}', flavor, shard) }}:
           flavor: ${{ flavor }}
           shard: ${{ shard }}
  steps:
  - script: go run test.go -shard $(shard) -flavor $(flavor) $(flags)
