// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vtctldata.proto

package vtctldata

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	logutil "vitess.io/vitess/go/vt/proto/logutil"
	topodata "vitess.io/vitess/go/vt/proto/topodata"
	vschema "vitess.io/vitess/go/vt/proto/vschema"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ExecuteVtctlCommandRequest is the payload for ExecuteVtctlCommand.
// timeouts are in nanoseconds.
type ExecuteVtctlCommandRequest struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	ActionTimeout        int64    `protobuf:"varint,2,opt,name=action_timeout,json=actionTimeout,proto3" json:"action_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteVtctlCommandRequest) Reset()         { *m = ExecuteVtctlCommandRequest{} }
func (m *ExecuteVtctlCommandRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteVtctlCommandRequest) ProtoMessage()    {}
func (*ExecuteVtctlCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{0}
}

func (m *ExecuteVtctlCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteVtctlCommandRequest.Unmarshal(m, b)
}
func (m *ExecuteVtctlCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteVtctlCommandRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteVtctlCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteVtctlCommandRequest.Merge(m, src)
}
func (m *ExecuteVtctlCommandRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteVtctlCommandRequest.Size(m)
}
func (m *ExecuteVtctlCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteVtctlCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteVtctlCommandRequest proto.InternalMessageInfo

func (m *ExecuteVtctlCommandRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecuteVtctlCommandRequest) GetActionTimeout() int64 {
	if m != nil {
		return m.ActionTimeout
	}
	return 0
}

// ExecuteVtctlCommandResponse is streamed back by ExecuteVtctlCommand.
type ExecuteVtctlCommandResponse struct {
	Event                *logutil.Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExecuteVtctlCommandResponse) Reset()         { *m = ExecuteVtctlCommandResponse{} }
func (m *ExecuteVtctlCommandResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteVtctlCommandResponse) ProtoMessage()    {}
func (*ExecuteVtctlCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{1}
}

func (m *ExecuteVtctlCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteVtctlCommandResponse.Unmarshal(m, b)
}
func (m *ExecuteVtctlCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteVtctlCommandResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteVtctlCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteVtctlCommandResponse.Merge(m, src)
}
func (m *ExecuteVtctlCommandResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteVtctlCommandResponse.Size(m)
}
func (m *ExecuteVtctlCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteVtctlCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteVtctlCommandResponse proto.InternalMessageInfo

func (m *ExecuteVtctlCommandResponse) GetEvent() *logutil.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type GetCellInfoNamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCellInfoNamesRequest) Reset()         { *m = GetCellInfoNamesRequest{} }
func (m *GetCellInfoNamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCellInfoNamesRequest) ProtoMessage()    {}
func (*GetCellInfoNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{2}
}

func (m *GetCellInfoNamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellInfoNamesRequest.Unmarshal(m, b)
}
func (m *GetCellInfoNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellInfoNamesRequest.Marshal(b, m, deterministic)
}
func (m *GetCellInfoNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellInfoNamesRequest.Merge(m, src)
}
func (m *GetCellInfoNamesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCellInfoNamesRequest.Size(m)
}
func (m *GetCellInfoNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellInfoNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellInfoNamesRequest proto.InternalMessageInfo

type GetCellInfoNamesResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCellInfoNamesResponse) Reset()         { *m = GetCellInfoNamesResponse{} }
func (m *GetCellInfoNamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCellInfoNamesResponse) ProtoMessage()    {}
func (*GetCellInfoNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{3}
}

func (m *GetCellInfoNamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellInfoNamesResponse.Unmarshal(m, b)
}
func (m *GetCellInfoNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellInfoNamesResponse.Marshal(b, m, deterministic)
}
func (m *GetCellInfoNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellInfoNamesResponse.Merge(m, src)
}
func (m *GetCellInfoNamesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCellInfoNamesResponse.Size(m)
}
func (m *GetCellInfoNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellInfoNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellInfoNamesResponse proto.InternalMessageInfo

func (m *GetCellInfoNamesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type GetCellInfoRequest struct {
	Cell                 string   `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCellInfoRequest) Reset()         { *m = GetCellInfoRequest{} }
func (m *GetCellInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCellInfoRequest) ProtoMessage()    {}
func (*GetCellInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{4}
}

func (m *GetCellInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellInfoRequest.Unmarshal(m, b)
}
func (m *GetCellInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetCellInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellInfoRequest.Merge(m, src)
}
func (m *GetCellInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCellInfoRequest.Size(m)
}
func (m *GetCellInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellInfoRequest proto.InternalMessageInfo

func (m *GetCellInfoRequest) GetCell() string {
	if m != nil {
		return m.Cell
	}
	return ""
}

type GetCellInfoResponse struct {
	CellInfo             *topodata.CellInfo `protobuf:"bytes,1,opt,name=cell_info,json=cellInfo,proto3" json:"cell_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetCellInfoResponse) Reset()         { *m = GetCellInfoResponse{} }
func (m *GetCellInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetCellInfoResponse) ProtoMessage()    {}
func (*GetCellInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{5}
}

func (m *GetCellInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellInfoResponse.Unmarshal(m, b)
}
func (m *GetCellInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetCellInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellInfoResponse.Merge(m, src)
}
func (m *GetCellInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetCellInfoResponse.Size(m)
}
func (m *GetCellInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellInfoResponse proto.InternalMessageInfo

func (m *GetCellInfoResponse) GetCellInfo() *topodata.CellInfo {
	if m != nil {
		return m.CellInfo
	}
	return nil
}

type GetCellsAliasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCellsAliasesRequest) Reset()         { *m = GetCellsAliasesRequest{} }
func (m *GetCellsAliasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCellsAliasesRequest) ProtoMessage()    {}
func (*GetCellsAliasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{6}
}

func (m *GetCellsAliasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellsAliasesRequest.Unmarshal(m, b)
}
func (m *GetCellsAliasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellsAliasesRequest.Marshal(b, m, deterministic)
}
func (m *GetCellsAliasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellsAliasesRequest.Merge(m, src)
}
func (m *GetCellsAliasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCellsAliasesRequest.Size(m)
}
func (m *GetCellsAliasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellsAliasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellsAliasesRequest proto.InternalMessageInfo

type GetCellsAliasesResponse struct {
	Aliases              map[string]*topodata.CellsAlias `protobuf:"bytes,1,rep,name=aliases,proto3" json:"aliases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetCellsAliasesResponse) Reset()         { *m = GetCellsAliasesResponse{} }
func (m *GetCellsAliasesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCellsAliasesResponse) ProtoMessage()    {}
func (*GetCellsAliasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{7}
}

func (m *GetCellsAliasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCellsAliasesResponse.Unmarshal(m, b)
}
func (m *GetCellsAliasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCellsAliasesResponse.Marshal(b, m, deterministic)
}
func (m *GetCellsAliasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCellsAliasesResponse.Merge(m, src)
}
func (m *GetCellsAliasesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCellsAliasesResponse.Size(m)
}
func (m *GetCellsAliasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCellsAliasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCellsAliasesResponse proto.InternalMessageInfo

func (m *GetCellsAliasesResponse) GetAliases() map[string]*topodata.CellsAlias {
	if m != nil {
		return m.Aliases
	}
	return nil
}

type GetKeyspacesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyspacesRequest) Reset()         { *m = GetKeyspacesRequest{} }
func (m *GetKeyspacesRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeyspacesRequest) ProtoMessage()    {}
func (*GetKeyspacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{8}
}

func (m *GetKeyspacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyspacesRequest.Unmarshal(m, b)
}
func (m *GetKeyspacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyspacesRequest.Marshal(b, m, deterministic)
}
func (m *GetKeyspacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyspacesRequest.Merge(m, src)
}
func (m *GetKeyspacesRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeyspacesRequest.Size(m)
}
func (m *GetKeyspacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyspacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyspacesRequest proto.InternalMessageInfo

type GetKeyspacesResponse struct {
	Keyspaces            []*Keyspace `protobuf:"bytes,1,rep,name=keyspaces,proto3" json:"keyspaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetKeyspacesResponse) Reset()         { *m = GetKeyspacesResponse{} }
func (m *GetKeyspacesResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeyspacesResponse) ProtoMessage()    {}
func (*GetKeyspacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{9}
}

func (m *GetKeyspacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyspacesResponse.Unmarshal(m, b)
}
func (m *GetKeyspacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyspacesResponse.Marshal(b, m, deterministic)
}
func (m *GetKeyspacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyspacesResponse.Merge(m, src)
}
func (m *GetKeyspacesResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeyspacesResponse.Size(m)
}
func (m *GetKeyspacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyspacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyspacesResponse proto.InternalMessageInfo

func (m *GetKeyspacesResponse) GetKeyspaces() []*Keyspace {
	if m != nil {
		return m.Keyspaces
	}
	return nil
}

type GetKeyspaceRequest struct {
	Keyspace             string   `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyspaceRequest) Reset()         { *m = GetKeyspaceRequest{} }
func (m *GetKeyspaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeyspaceRequest) ProtoMessage()    {}
func (*GetKeyspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{10}
}

func (m *GetKeyspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyspaceRequest.Unmarshal(m, b)
}
func (m *GetKeyspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyspaceRequest.Marshal(b, m, deterministic)
}
func (m *GetKeyspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyspaceRequest.Merge(m, src)
}
func (m *GetKeyspaceRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeyspaceRequest.Size(m)
}
func (m *GetKeyspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyspaceRequest proto.InternalMessageInfo

func (m *GetKeyspaceRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type GetKeyspaceResponse struct {
	Keyspace             *Keyspace `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetKeyspaceResponse) Reset()         { *m = GetKeyspaceResponse{} }
func (m *GetKeyspaceResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeyspaceResponse) ProtoMessage()    {}
func (*GetKeyspaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{11}
}

func (m *GetKeyspaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyspaceResponse.Unmarshal(m, b)
}
func (m *GetKeyspaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyspaceResponse.Marshal(b, m, deterministic)
}
func (m *GetKeyspaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyspaceResponse.Merge(m, src)
}
func (m *GetKeyspaceResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeyspaceResponse.Size(m)
}
func (m *GetKeyspaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyspaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyspaceResponse proto.InternalMessageInfo

func (m *GetKeyspaceResponse) GetKeyspace() *Keyspace {
	if m != nil {
		return m.Keyspace
	}
	return nil
}

type GetSrvVSchemaRequest struct {
	Cell                 string   `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSrvVSchemaRequest) Reset()         { *m = GetSrvVSchemaRequest{} }
func (m *GetSrvVSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*GetSrvVSchemaRequest) ProtoMessage()    {}
func (*GetSrvVSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{12}
}

func (m *GetSrvVSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSrvVSchemaRequest.Unmarshal(m, b)
}
func (m *GetSrvVSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSrvVSchemaRequest.Marshal(b, m, deterministic)
}
func (m *GetSrvVSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSrvVSchemaRequest.Merge(m, src)
}
func (m *GetSrvVSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_GetSrvVSchemaRequest.Size(m)
}
func (m *GetSrvVSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSrvVSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSrvVSchemaRequest proto.InternalMessageInfo

func (m *GetSrvVSchemaRequest) GetCell() string {
	if m != nil {
		return m.Cell
	}
	return ""
}

type GetSrvVSchemaResponse struct {
	SrvVSchema           *vschema.SrvVSchema `protobuf:"bytes,1,opt,name=srv_v_schema,json=srvVSchema,proto3" json:"srv_v_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSrvVSchemaResponse) Reset()         { *m = GetSrvVSchemaResponse{} }
func (m *GetSrvVSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*GetSrvVSchemaResponse) ProtoMessage()    {}
func (*GetSrvVSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{13}
}

func (m *GetSrvVSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSrvVSchemaResponse.Unmarshal(m, b)
}
func (m *GetSrvVSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSrvVSchemaResponse.Marshal(b, m, deterministic)
}
func (m *GetSrvVSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSrvVSchemaResponse.Merge(m, src)
}
func (m *GetSrvVSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_GetSrvVSchemaResponse.Size(m)
}
func (m *GetSrvVSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSrvVSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSrvVSchemaResponse proto.InternalMessageInfo

func (m *GetSrvVSchemaResponse) GetSrvVSchema() *vschema.SrvVSchema {
	if m != nil {
		return m.SrvVSchema
	}
	return nil
}

type GetTabletRequest struct {
	TabletAlias          *topodata.TabletAlias `protobuf:"bytes,1,opt,name=tablet_alias,json=tabletAlias,proto3" json:"tablet_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetTabletRequest) Reset()         { *m = GetTabletRequest{} }
func (m *GetTabletRequest) String() string { return proto.CompactTextString(m) }
func (*GetTabletRequest) ProtoMessage()    {}
func (*GetTabletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{14}
}

func (m *GetTabletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTabletRequest.Unmarshal(m, b)
}
func (m *GetTabletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTabletRequest.Marshal(b, m, deterministic)
}
func (m *GetTabletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTabletRequest.Merge(m, src)
}
func (m *GetTabletRequest) XXX_Size() int {
	return xxx_messageInfo_GetTabletRequest.Size(m)
}
func (m *GetTabletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTabletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTabletRequest proto.InternalMessageInfo

func (m *GetTabletRequest) GetTabletAlias() *topodata.TabletAlias {
	if m != nil {
		return m.TabletAlias
	}
	return nil
}

type GetTabletResponse struct {
	Tablet               *topodata.Tablet `protobuf:"bytes,1,opt,name=tablet,proto3" json:"tablet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTabletResponse) Reset()         { *m = GetTabletResponse{} }
func (m *GetTabletResponse) String() string { return proto.CompactTextString(m) }
func (*GetTabletResponse) ProtoMessage()    {}
func (*GetTabletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{15}
}

func (m *GetTabletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTabletResponse.Unmarshal(m, b)
}
func (m *GetTabletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTabletResponse.Marshal(b, m, deterministic)
}
func (m *GetTabletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTabletResponse.Merge(m, src)
}
func (m *GetTabletResponse) XXX_Size() int {
	return xxx_messageInfo_GetTabletResponse.Size(m)
}
func (m *GetTabletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTabletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTabletResponse proto.InternalMessageInfo

func (m *GetTabletResponse) GetTablet() *topodata.Tablet {
	if m != nil {
		return m.Tablet
	}
	return nil
}

type GetTabletsRequest struct {
	// Keyspace is the name of the keyspace to return tablets for. Omit to return
	// all tablets.
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	// Shard is the name of the shard to return tablets for. This field is ignored
	// if Keyspace is not set.
	Shard string `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	// Cells is an optional set of cells to return tablets for.
	Cells                []string `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTabletsRequest) Reset()         { *m = GetTabletsRequest{} }
func (m *GetTabletsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTabletsRequest) ProtoMessage()    {}
func (*GetTabletsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{16}
}

func (m *GetTabletsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTabletsRequest.Unmarshal(m, b)
}
func (m *GetTabletsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTabletsRequest.Marshal(b, m, deterministic)
}
func (m *GetTabletsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTabletsRequest.Merge(m, src)
}
func (m *GetTabletsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTabletsRequest.Size(m)
}
func (m *GetTabletsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTabletsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTabletsRequest proto.InternalMessageInfo

func (m *GetTabletsRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *GetTabletsRequest) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *GetTabletsRequest) GetCells() []string {
	if m != nil {
		return m.Cells
	}
	return nil
}

type GetTabletsResponse struct {
	Tablets              []*topodata.Tablet `protobuf:"bytes,1,rep,name=tablets,proto3" json:"tablets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTabletsResponse) Reset()         { *m = GetTabletsResponse{} }
func (m *GetTabletsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTabletsResponse) ProtoMessage()    {}
func (*GetTabletsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{17}
}

func (m *GetTabletsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTabletsResponse.Unmarshal(m, b)
}
func (m *GetTabletsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTabletsResponse.Marshal(b, m, deterministic)
}
func (m *GetTabletsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTabletsResponse.Merge(m, src)
}
func (m *GetTabletsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTabletsResponse.Size(m)
}
func (m *GetTabletsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTabletsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTabletsResponse proto.InternalMessageInfo

func (m *GetTabletsResponse) GetTablets() []*topodata.Tablet {
	if m != nil {
		return m.Tablets
	}
	return nil
}

type Keyspace struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keyspace             *topodata.Keyspace `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Keyspace) Reset()         { *m = Keyspace{} }
func (m *Keyspace) String() string { return proto.CompactTextString(m) }
func (*Keyspace) ProtoMessage()    {}
func (*Keyspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{18}
}

func (m *Keyspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyspace.Unmarshal(m, b)
}
func (m *Keyspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyspace.Marshal(b, m, deterministic)
}
func (m *Keyspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyspace.Merge(m, src)
}
func (m *Keyspace) XXX_Size() int {
	return xxx_messageInfo_Keyspace.Size(m)
}
func (m *Keyspace) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyspace.DiscardUnknown(m)
}

var xxx_messageInfo_Keyspace proto.InternalMessageInfo

func (m *Keyspace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Keyspace) GetKeyspace() *topodata.Keyspace {
	if m != nil {
		return m.Keyspace
	}
	return nil
}

type FindAllShardsInKeyspaceRequest struct {
	Keyspace             string   `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllShardsInKeyspaceRequest) Reset()         { *m = FindAllShardsInKeyspaceRequest{} }
func (m *FindAllShardsInKeyspaceRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllShardsInKeyspaceRequest) ProtoMessage()    {}
func (*FindAllShardsInKeyspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{19}
}

func (m *FindAllShardsInKeyspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllShardsInKeyspaceRequest.Unmarshal(m, b)
}
func (m *FindAllShardsInKeyspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllShardsInKeyspaceRequest.Marshal(b, m, deterministic)
}
func (m *FindAllShardsInKeyspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllShardsInKeyspaceRequest.Merge(m, src)
}
func (m *FindAllShardsInKeyspaceRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllShardsInKeyspaceRequest.Size(m)
}
func (m *FindAllShardsInKeyspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllShardsInKeyspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllShardsInKeyspaceRequest proto.InternalMessageInfo

func (m *FindAllShardsInKeyspaceRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type FindAllShardsInKeyspaceResponse struct {
	Shards               map[string]*Shard `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FindAllShardsInKeyspaceResponse) Reset()         { *m = FindAllShardsInKeyspaceResponse{} }
func (m *FindAllShardsInKeyspaceResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllShardsInKeyspaceResponse) ProtoMessage()    {}
func (*FindAllShardsInKeyspaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{20}
}

func (m *FindAllShardsInKeyspaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllShardsInKeyspaceResponse.Unmarshal(m, b)
}
func (m *FindAllShardsInKeyspaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllShardsInKeyspaceResponse.Marshal(b, m, deterministic)
}
func (m *FindAllShardsInKeyspaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllShardsInKeyspaceResponse.Merge(m, src)
}
func (m *FindAllShardsInKeyspaceResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllShardsInKeyspaceResponse.Size(m)
}
func (m *FindAllShardsInKeyspaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllShardsInKeyspaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllShardsInKeyspaceResponse proto.InternalMessageInfo

func (m *FindAllShardsInKeyspaceResponse) GetShards() map[string]*Shard {
	if m != nil {
		return m.Shards
	}
	return nil
}

type Shard struct {
	Keyspace             string          `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Shard                *topodata.Shard `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Shard) Reset()         { *m = Shard{} }
func (m *Shard) String() string { return proto.CompactTextString(m) }
func (*Shard) ProtoMessage()    {}
func (*Shard) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{21}
}

func (m *Shard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shard.Unmarshal(m, b)
}
func (m *Shard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shard.Marshal(b, m, deterministic)
}
func (m *Shard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shard.Merge(m, src)
}
func (m *Shard) XXX_Size() int {
	return xxx_messageInfo_Shard.Size(m)
}
func (m *Shard) XXX_DiscardUnknown() {
	xxx_messageInfo_Shard.DiscardUnknown(m)
}

var xxx_messageInfo_Shard proto.InternalMessageInfo

func (m *Shard) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Shard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shard) GetShard() *topodata.Shard {
	if m != nil {
		return m.Shard
	}
	return nil
}

// TableMaterializeSttings contains the settings for one table.
type TableMaterializeSettings struct {
	TargetTable string `protobuf:"bytes,1,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"`
	// source_expression is a select statement.
	SourceExpression string `protobuf:"bytes,2,opt,name=source_expression,json=sourceExpression,proto3" json:"source_expression,omitempty"`
	// create_ddl contains the DDL to create the target table.
	// If empty, the target table must already exist.
	// if "copy", the target table DDL is the same as the source table.
	CreateDdl            string   `protobuf:"bytes,3,opt,name=create_ddl,json=createDdl,proto3" json:"create_ddl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableMaterializeSettings) Reset()         { *m = TableMaterializeSettings{} }
func (m *TableMaterializeSettings) String() string { return proto.CompactTextString(m) }
func (*TableMaterializeSettings) ProtoMessage()    {}
func (*TableMaterializeSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{22}
}

func (m *TableMaterializeSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableMaterializeSettings.Unmarshal(m, b)
}
func (m *TableMaterializeSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableMaterializeSettings.Marshal(b, m, deterministic)
}
func (m *TableMaterializeSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableMaterializeSettings.Merge(m, src)
}
func (m *TableMaterializeSettings) XXX_Size() int {
	return xxx_messageInfo_TableMaterializeSettings.Size(m)
}
func (m *TableMaterializeSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_TableMaterializeSettings.DiscardUnknown(m)
}

var xxx_messageInfo_TableMaterializeSettings proto.InternalMessageInfo

func (m *TableMaterializeSettings) GetTargetTable() string {
	if m != nil {
		return m.TargetTable
	}
	return ""
}

func (m *TableMaterializeSettings) GetSourceExpression() string {
	if m != nil {
		return m.SourceExpression
	}
	return ""
}

func (m *TableMaterializeSettings) GetCreateDdl() string {
	if m != nil {
		return m.CreateDdl
	}
	return ""
}

// MaterializeSettings contains the settings for the Materialize command.
type MaterializeSettings struct {
	// workflow is the name of the workflow.
	Workflow       string `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	SourceKeyspace string `protobuf:"bytes,2,opt,name=source_keyspace,json=sourceKeyspace,proto3" json:"source_keyspace,omitempty"`
	TargetKeyspace string `protobuf:"bytes,3,opt,name=target_keyspace,json=targetKeyspace,proto3" json:"target_keyspace,omitempty"`
	// stop_after_copy specifies if vreplication should be stopped after copying.
	StopAfterCopy bool                        `protobuf:"varint,4,opt,name=stop_after_copy,json=stopAfterCopy,proto3" json:"stop_after_copy,omitempty"`
	TableSettings []*TableMaterializeSettings `protobuf:"bytes,5,rep,name=table_settings,json=tableSettings,proto3" json:"table_settings,omitempty"`
	// optional parameters.
	Cell                 string   `protobuf:"bytes,6,opt,name=cell,proto3" json:"cell,omitempty"`
	TabletTypes          string   `protobuf:"bytes,7,opt,name=tablet_types,json=tabletTypes,proto3" json:"tablet_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaterializeSettings) Reset()         { *m = MaterializeSettings{} }
func (m *MaterializeSettings) String() string { return proto.CompactTextString(m) }
func (*MaterializeSettings) ProtoMessage()    {}
func (*MaterializeSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_f41247b323a1ab2e, []int{23}
}

func (m *MaterializeSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterializeSettings.Unmarshal(m, b)
}
func (m *MaterializeSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterializeSettings.Marshal(b, m, deterministic)
}
func (m *MaterializeSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterializeSettings.Merge(m, src)
}
func (m *MaterializeSettings) XXX_Size() int {
	return xxx_messageInfo_MaterializeSettings.Size(m)
}
func (m *MaterializeSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterializeSettings.DiscardUnknown(m)
}

var xxx_messageInfo_MaterializeSettings proto.InternalMessageInfo

func (m *MaterializeSettings) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *MaterializeSettings) GetSourceKeyspace() string {
	if m != nil {
		return m.SourceKeyspace
	}
	return ""
}

func (m *MaterializeSettings) GetTargetKeyspace() string {
	if m != nil {
		return m.TargetKeyspace
	}
	return ""
}

func (m *MaterializeSettings) GetStopAfterCopy() bool {
	if m != nil {
		return m.StopAfterCopy
	}
	return false
}

func (m *MaterializeSettings) GetTableSettings() []*TableMaterializeSettings {
	if m != nil {
		return m.TableSettings
	}
	return nil
}

func (m *MaterializeSettings) GetCell() string {
	if m != nil {
		return m.Cell
	}
	return ""
}

func (m *MaterializeSettings) GetTabletTypes() string {
	if m != nil {
		return m.TabletTypes
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecuteVtctlCommandRequest)(nil), "vtctldata.ExecuteVtctlCommandRequest")
	proto.RegisterType((*ExecuteVtctlCommandResponse)(nil), "vtctldata.ExecuteVtctlCommandResponse")
	proto.RegisterType((*GetCellInfoNamesRequest)(nil), "vtctldata.GetCellInfoNamesRequest")
	proto.RegisterType((*GetCellInfoNamesResponse)(nil), "vtctldata.GetCellInfoNamesResponse")
	proto.RegisterType((*GetCellInfoRequest)(nil), "vtctldata.GetCellInfoRequest")
	proto.RegisterType((*GetCellInfoResponse)(nil), "vtctldata.GetCellInfoResponse")
	proto.RegisterType((*GetCellsAliasesRequest)(nil), "vtctldata.GetCellsAliasesRequest")
	proto.RegisterType((*GetCellsAliasesResponse)(nil), "vtctldata.GetCellsAliasesResponse")
	proto.RegisterMapType((map[string]*topodata.CellsAlias)(nil), "vtctldata.GetCellsAliasesResponse.AliasesEntry")
	proto.RegisterType((*GetKeyspacesRequest)(nil), "vtctldata.GetKeyspacesRequest")
	proto.RegisterType((*GetKeyspacesResponse)(nil), "vtctldata.GetKeyspacesResponse")
	proto.RegisterType((*GetKeyspaceRequest)(nil), "vtctldata.GetKeyspaceRequest")
	proto.RegisterType((*GetKeyspaceResponse)(nil), "vtctldata.GetKeyspaceResponse")
	proto.RegisterType((*GetSrvVSchemaRequest)(nil), "vtctldata.GetSrvVSchemaRequest")
	proto.RegisterType((*GetSrvVSchemaResponse)(nil), "vtctldata.GetSrvVSchemaResponse")
	proto.RegisterType((*GetTabletRequest)(nil), "vtctldata.GetTabletRequest")
	proto.RegisterType((*GetTabletResponse)(nil), "vtctldata.GetTabletResponse")
	proto.RegisterType((*GetTabletsRequest)(nil), "vtctldata.GetTabletsRequest")
	proto.RegisterType((*GetTabletsResponse)(nil), "vtctldata.GetTabletsResponse")
	proto.RegisterType((*Keyspace)(nil), "vtctldata.Keyspace")
	proto.RegisterType((*FindAllShardsInKeyspaceRequest)(nil), "vtctldata.FindAllShardsInKeyspaceRequest")
	proto.RegisterType((*FindAllShardsInKeyspaceResponse)(nil), "vtctldata.FindAllShardsInKeyspaceResponse")
	proto.RegisterMapType((map[string]*Shard)(nil), "vtctldata.FindAllShardsInKeyspaceResponse.ShardsEntry")
	proto.RegisterType((*Shard)(nil), "vtctldata.Shard")
	proto.RegisterType((*TableMaterializeSettings)(nil), "vtctldata.TableMaterializeSettings")
	proto.RegisterType((*MaterializeSettings)(nil), "vtctldata.MaterializeSettings")
}

func init() { proto.RegisterFile("vtctldata.proto", fileDescriptor_f41247b323a1ab2e) }

var fileDescriptor_f41247b323a1ab2e = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0x77, 0xbb, 0xc9, 0xfa, 0x6c, 0xf6, 0xa7, 0x4e, 0x02, 0xc6, 0x08, 0x08, 0x03, 0x4d,
	0x57, 0x41, 0xf2, 0x96, 0x20, 0x50, 0x85, 0x40, 0x22, 0x84, 0xb4, 0x0a, 0x85, 0x08, 0x39, 0x51,
	0x91, 0x40, 0xc2, 0x9a, 0x7a, 0x27, 0x5b, 0x2b, 0xb3, 0x1e, 0xe3, 0x99, 0x75, 0xbb, 0xbc, 0x01,
	0x2f, 0xc3, 0x25, 0x97, 0x3c, 0x1b, 0x9a, 0x3f, 0xdb, 0x9b, 0xee, 0x16, 0x7a, 0x37, 0xf3, 0x9d,
	0xbf, 0xef, 0x9c, 0x6f, 0x8e, 0x65, 0x18, 0x96, 0x22, 0x11, 0x74, 0x8a, 0x05, 0x0e, 0xf3, 0x82,
	0x09, 0xe6, 0xb9, 0x15, 0x10, 0xf4, 0x29, 0x9b, 0x2d, 0x44, 0x4a, 0xb5, 0x25, 0x18, 0x08, 0x96,
	0xb3, 0xda, 0x33, 0xe8, 0x97, 0x3c, 0x79, 0x4e, 0xe6, 0xe6, 0x8a, 0x7e, 0x86, 0xe0, 0xec, 0x25,
	0x49, 0x16, 0x82, 0x3c, 0x95, 0x19, 0x4e, 0xd9, 0x7c, 0x8e, 0xb3, 0x69, 0x44, 0x7e, 0x5f, 0x10,
	0x2e, 0x3c, 0x0f, 0xee, 0xe0, 0x62, 0xc6, 0x7d, 0xe7, 0xa0, 0x3d, 0x76, 0x23, 0x75, 0xf6, 0xee,
	0xc1, 0x00, 0x27, 0x22, 0x65, 0x59, 0x2c, 0xd2, 0x39, 0x61, 0x0b, 0xe1, 0xb7, 0x0e, 0x9c, 0x71,
	0x3b, 0xea, 0x6b, 0xf4, 0x4a, 0x83, 0xe8, 0x14, 0xde, 0x5d, 0x9b, 0x98, 0xe7, 0x2c, 0xe3, 0xc4,
	0xfb, 0x18, 0x3a, 0xa4, 0x24, 0x99, 0xf0, 0x9d, 0x03, 0x67, 0xdc, 0x3b, 0x1e, 0x84, 0x96, 0xf5,
	0x99, 0x44, 0x23, 0x6d, 0x44, 0xef, 0xc0, 0xdb, 0x8f, 0x89, 0x38, 0x25, 0x94, 0x9e, 0x67, 0xd7,
	0xec, 0x02, 0xcf, 0x09, 0x37, 0xd4, 0xd0, 0x03, 0xf0, 0x5f, 0x35, 0x99, 0xe4, 0x7b, 0xd0, 0xc9,
	0x24, 0x60, 0x78, 0xeb, 0x0b, 0x1a, 0x83, 0xd7, 0x88, 0x68, 0xb4, 0x98, 0x10, 0x4a, 0x15, 0x0f,
	0x37, 0x52, 0x67, 0xf4, 0x08, 0x76, 0x57, 0x3c, 0x4d, 0xda, 0x09, 0xb8, 0xd2, 0x1c, 0xa7, 0xd9,
	0x35, 0x33, 0xbc, 0xbd, 0xb0, 0x1a, 0x6f, 0xe5, 0xde, 0x4d, 0xcc, 0x09, 0xf9, 0xf0, 0x96, 0xc9,
	0xc3, 0x4f, 0x68, 0x8a, 0x79, 0xcd, 0xfe, 0x6f, 0xa7, 0xea, 0xac, 0x36, 0x99, 0x32, 0xe7, 0xb0,
	0x8d, 0x35, 0xa4, 0xf8, 0xf7, 0x8e, 0x27, 0x61, 0x2d, 0xf7, 0x86, 0xa0, 0xd0, 0xdc, 0xcf, 0x32,
	0x51, 0x2c, 0x23, 0x1b, 0x1f, 0xfc, 0x04, 0x3b, 0x4d, 0x83, 0x37, 0x82, 0xf6, 0x0d, 0x59, 0x9a,
	0x5e, 0xe5, 0xd1, 0x3b, 0x82, 0x4e, 0x89, 0xe9, 0x82, 0x28, 0x11, 0x7b, 0xc7, 0x7b, 0xab, 0xfd,
	0xe8, 0x32, 0x91, 0x76, 0xf9, 0xb2, 0xf5, 0xd0, 0x41, 0xfb, 0x6a, 0x34, 0x4f, 0xc8, 0x92, 0xe7,
	0x38, 0xa9, 0xfb, 0x39, 0x87, 0xbd, 0x55, 0xd8, 0xf4, 0xf2, 0x29, 0xb8, 0x37, 0x16, 0x34, 0xdd,
	0xec, 0x36, 0xba, 0xb1, 0x01, 0x51, 0xed, 0x85, 0x1e, 0x28, 0x99, 0x2a, 0x8b, 0x91, 0x29, 0x80,
	0xae, 0x75, 0x31, 0xf4, 0xab, 0xbb, 0x91, 0xab, 0x8e, 0xa8, 0xe4, 0x5a, 0x0d, 0xd9, 0x50, 0xba,
	0xce, 0x73, 0xa4, 0x9a, 0xb8, 0x2c, 0xca, 0xa7, 0x97, 0x6a, 0x45, 0x5e, 0xf7, 0x44, 0x2e, 0x60,
	0xff, 0x96, 0xaf, 0xa9, 0xfa, 0x39, 0xec, 0xf0, 0xa2, 0x8c, 0xcb, 0x58, 0xaf, 0x59, 0x5d, 0xd9,
	0xac, 0x5d, 0x23, 0x04, 0x78, 0x75, 0x46, 0x3f, 0xc0, 0xe8, 0x31, 0x11, 0x57, 0xf8, 0x19, 0x25,
	0xc2, 0xd6, 0x7d, 0x08, 0x3b, 0x42, 0x01, 0xb1, 0xd2, 0xd3, 0xa4, 0xda, 0xaf, 0x25, 0xd2, 0xee,
	0x5a, 0xa3, 0x9e, 0xa8, 0x2f, 0xe8, 0x6b, 0xb8, 0xdb, 0xc8, 0x66, 0x98, 0x8d, 0x61, 0x4b, 0xfb,
	0x98, 0x44, 0xa3, 0xdb, 0x89, 0x22, 0x63, 0x47, 0xbf, 0x36, 0xc2, 0xf9, 0xff, 0x50, 0x40, 0x2e,
	0x1c, 0x7f, 0x8e, 0x8b, 0xa9, 0x7a, 0x45, 0x6e, 0xa4, 0x2f, 0x12, 0x95, 0xb3, 0xe2, 0x7e, 0x5b,
	0xaf, 0xa1, 0xba, 0xa0, 0x6f, 0x94, 0xbe, 0x55, 0x72, 0x43, 0xee, 0x08, 0xb6, 0x75, 0x71, 0xfb,
	0x4c, 0x5e, 0x65, 0x67, 0x1d, 0xd0, 0x05, 0x74, 0xad, 0x7a, 0x52, 0x1b, 0xb9, 0xdd, 0x56, 0x1b,
	0x79, 0xf6, 0xc2, 0x06, 0xd3, 0xd6, 0xed, 0x35, 0x5d, 0xa3, 0xfb, 0x57, 0xf0, 0xfe, 0xa3, 0x34,
	0x9b, 0x9e, 0x50, 0x7a, 0x29, 0x79, 0xf3, 0xf3, 0xec, 0x4d, 0x5e, 0xdf, 0x3f, 0x0e, 0x7c, 0xb0,
	0x31, 0xdc, 0x74, 0x77, 0x01, 0x5b, 0x6a, 0x24, 0xb6, 0xb9, 0x2f, 0x1a, 0x0f, 0xf1, 0x3f, 0x62,
	0x43, 0x6d, 0xd0, 0x8b, 0x6d, 0xb2, 0x04, 0x4f, 0xa0, 0xd7, 0x80, 0xd7, 0xac, 0xf5, 0xe1, 0xea,
	0x5a, 0x8f, 0x1a, 0xf5, 0x54, 0x60, 0x73, 0xa5, 0x7f, 0x83, 0x8e, 0xc2, 0x5e, 0xab, 0xb0, 0x9d,
	0x73, 0xab, 0x31, 0xe7, 0x7b, 0x56, 0xf5, 0xb6, 0x2a, 0x32, 0xac, 0x87, 0x6c, 0x6a, 0x28, 0x2b,
	0xfa, 0xd3, 0x01, 0x5f, 0x49, 0xf8, 0x23, 0x16, 0xa4, 0x48, 0x31, 0x4d, 0xff, 0x20, 0x97, 0x44,
	0x88, 0x34, 0x9b, 0x71, 0xef, 0x43, 0xf9, 0xc6, 0x8b, 0x19, 0x11, 0xb1, 0x52, 0xd7, 0xd4, 0xed,
	0x69, 0x4c, 0x45, 0x79, 0x9f, 0xc0, 0x5d, 0xce, 0x16, 0x45, 0x42, 0x62, 0xf2, 0x32, 0x2f, 0x08,
	0xe7, 0x29, 0xcb, 0x0c, 0x8f, 0x91, 0x36, 0x9c, 0x55, 0xb8, 0xf7, 0x1e, 0x40, 0x52, 0x10, 0x2c,
	0x48, 0x3c, 0x9d, 0x52, 0x45, 0xcc, 0x8d, 0x5c, 0x8d, 0x7c, 0x37, 0xa5, 0xe8, 0xaf, 0x16, 0xec,
	0xae, 0xa3, 0x11, 0x40, 0xf7, 0x05, 0x2b, 0x6e, 0xae, 0x29, 0x7b, 0x61, 0x5b, 0xb7, 0x77, 0xef,
	0x3e, 0x0c, 0x4d, 0xfd, 0x95, 0x57, 0xe5, 0x46, 0x03, 0x0d, 0x57, 0x6f, 0xf1, 0x3e, 0x0c, 0x4d,
	0x2f, 0x95, 0xa3, 0x26, 0x30, 0xd0, 0x70, 0xe5, 0x78, 0x08, 0x43, 0x2e, 0x58, 0x1e, 0xe3, 0x6b,
	0x41, 0x8a, 0x38, 0x61, 0xf9, 0xd2, 0xbf, 0x73, 0xe0, 0x8c, 0xbb, 0x51, 0x5f, 0xc2, 0x27, 0x12,
	0x3d, 0x65, 0xf9, 0xd2, 0xfb, 0x1e, 0x06, 0x6a, 0x2a, 0x31, 0x37, 0x3c, 0xfd, 0x8e, 0x7a, 0x3e,
	0x1f, 0x35, 0xe4, 0xdc, 0x34, 0xd9, 0xa8, 0xaf, 0x42, 0xab, 0x0e, 0xed, 0x47, 0x6c, 0xab, 0xfe,
	0x88, 0xe9, 0xe1, 0xab, 0x0f, 0x8c, 0x58, 0xe6, 0x84, 0xfb, 0xdb, 0x76, 0xf8, 0x12, 0xbb, 0x92,
	0xd0, 0xb7, 0xe3, 0x5f, 0x0e, 0xcb, 0x54, 0x10, 0xce, 0xc3, 0x94, 0x4d, 0xf4, 0x69, 0x32, 0x63,
	0x93, 0x52, 0x4c, 0xd4, 0xff, 0xc3, 0xa4, 0x22, 0xf2, 0x6c, 0x4b, 0x01, 0x9f, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x5e, 0x26, 0x9e, 0x9c, 0x08, 0x00, 0x00,
}
