// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysqlctl.proto

package mysqlctl

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	topodata "vitess.io/vitess/go/vt/proto/topodata"
	vttime "vitess.io/vitess/go/vt/proto/vttime"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status is an enum representing the possible status of a backup.
type BackupInfo_Status int32

const (
	BackupInfo_UNKNOWN    BackupInfo_Status = 0
	BackupInfo_INCOMPLETE BackupInfo_Status = 1
	BackupInfo_COMPLETE   BackupInfo_Status = 2
	// A backup status of INVALID should be set if the backup is complete
	// but unusable in some way (partial upload, corrupt file, etc).
	BackupInfo_INVALID BackupInfo_Status = 3
	// A backup status of VALID should be set if the backup is both
	// complete and usuable.
	BackupInfo_VALID BackupInfo_Status = 4
)

var BackupInfo_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "INCOMPLETE",
	2: "COMPLETE",
	3: "INVALID",
	4: "VALID",
}

var BackupInfo_Status_value = map[string]int32{
	"UNKNOWN":    0,
	"INCOMPLETE": 1,
	"COMPLETE":   2,
	"INVALID":    3,
	"VALID":      4,
}

func (x BackupInfo_Status) String() string {
	return proto.EnumName(BackupInfo_Status_name, int32(x))
}

func (BackupInfo_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{10, 0}
}

type StartRequest struct {
	MysqldArgs           []string `protobuf:"bytes,1,rep,name=mysqld_args,json=mysqldArgs,proto3" json:"mysqld_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetMysqldArgs() []string {
	if m != nil {
		return m.MysqldArgs
	}
	return nil
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type ShutdownRequest struct {
	WaitForMysqld        bool     `protobuf:"varint,1,opt,name=wait_for_mysqld,json=waitForMysqld,proto3" json:"wait_for_mysqld,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{2}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

func (m *ShutdownRequest) GetWaitForMysqld() bool {
	if m != nil {
		return m.WaitForMysqld
	}
	return false
}

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{3}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

type RunMysqlUpgradeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunMysqlUpgradeRequest) Reset()         { *m = RunMysqlUpgradeRequest{} }
func (m *RunMysqlUpgradeRequest) String() string { return proto.CompactTextString(m) }
func (*RunMysqlUpgradeRequest) ProtoMessage()    {}
func (*RunMysqlUpgradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{4}
}

func (m *RunMysqlUpgradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMysqlUpgradeRequest.Unmarshal(m, b)
}
func (m *RunMysqlUpgradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMysqlUpgradeRequest.Marshal(b, m, deterministic)
}
func (m *RunMysqlUpgradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMysqlUpgradeRequest.Merge(m, src)
}
func (m *RunMysqlUpgradeRequest) XXX_Size() int {
	return xxx_messageInfo_RunMysqlUpgradeRequest.Size(m)
}
func (m *RunMysqlUpgradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMysqlUpgradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunMysqlUpgradeRequest proto.InternalMessageInfo

type RunMysqlUpgradeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunMysqlUpgradeResponse) Reset()         { *m = RunMysqlUpgradeResponse{} }
func (m *RunMysqlUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*RunMysqlUpgradeResponse) ProtoMessage()    {}
func (*RunMysqlUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{5}
}

func (m *RunMysqlUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMysqlUpgradeResponse.Unmarshal(m, b)
}
func (m *RunMysqlUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMysqlUpgradeResponse.Marshal(b, m, deterministic)
}
func (m *RunMysqlUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMysqlUpgradeResponse.Merge(m, src)
}
func (m *RunMysqlUpgradeResponse) XXX_Size() int {
	return xxx_messageInfo_RunMysqlUpgradeResponse.Size(m)
}
func (m *RunMysqlUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMysqlUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunMysqlUpgradeResponse proto.InternalMessageInfo

type ReinitConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReinitConfigRequest) Reset()         { *m = ReinitConfigRequest{} }
func (m *ReinitConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ReinitConfigRequest) ProtoMessage()    {}
func (*ReinitConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{6}
}

func (m *ReinitConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReinitConfigRequest.Unmarshal(m, b)
}
func (m *ReinitConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReinitConfigRequest.Marshal(b, m, deterministic)
}
func (m *ReinitConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReinitConfigRequest.Merge(m, src)
}
func (m *ReinitConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ReinitConfigRequest.Size(m)
}
func (m *ReinitConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReinitConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReinitConfigRequest proto.InternalMessageInfo

type ReinitConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReinitConfigResponse) Reset()         { *m = ReinitConfigResponse{} }
func (m *ReinitConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ReinitConfigResponse) ProtoMessage()    {}
func (*ReinitConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{7}
}

func (m *ReinitConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReinitConfigResponse.Unmarshal(m, b)
}
func (m *ReinitConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReinitConfigResponse.Marshal(b, m, deterministic)
}
func (m *ReinitConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReinitConfigResponse.Merge(m, src)
}
func (m *ReinitConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ReinitConfigResponse.Size(m)
}
func (m *ReinitConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReinitConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReinitConfigResponse proto.InternalMessageInfo

type RefreshConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshConfigRequest) Reset()         { *m = RefreshConfigRequest{} }
func (m *RefreshConfigRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshConfigRequest) ProtoMessage()    {}
func (*RefreshConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{8}
}

func (m *RefreshConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshConfigRequest.Unmarshal(m, b)
}
func (m *RefreshConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshConfigRequest.Marshal(b, m, deterministic)
}
func (m *RefreshConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshConfigRequest.Merge(m, src)
}
func (m *RefreshConfigRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshConfigRequest.Size(m)
}
func (m *RefreshConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshConfigRequest proto.InternalMessageInfo

type RefreshConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshConfigResponse) Reset()         { *m = RefreshConfigResponse{} }
func (m *RefreshConfigResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshConfigResponse) ProtoMessage()    {}
func (*RefreshConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{9}
}

func (m *RefreshConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshConfigResponse.Unmarshal(m, b)
}
func (m *RefreshConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshConfigResponse.Marshal(b, m, deterministic)
}
func (m *RefreshConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshConfigResponse.Merge(m, src)
}
func (m *RefreshConfigResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshConfigResponse.Size(m)
}
func (m *RefreshConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshConfigResponse proto.InternalMessageInfo

// BackupInfo is the read-only attributes of a mysqlctl/backupstorage.BackupHandle.
type BackupInfo struct {
	Name        string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directory   string                `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`
	Keyspace    string                `protobuf:"bytes,3,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Shard       string                `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	TabletAlias *topodata.TabletAlias `protobuf:"bytes,5,opt,name=tablet_alias,json=tabletAlias,proto3" json:"tablet_alias,omitempty"`
	Time        *vttime.Time          `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	// Engine is the name of the backupengine implementation used to create
	// this backup.
	Engine               string            `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"`
	Status               BackupInfo_Status `protobuf:"varint,8,opt,name=status,proto3,enum=mysqlctl.BackupInfo_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackupInfo) Reset()         { *m = BackupInfo{} }
func (m *BackupInfo) String() string { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()    {}
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c110e42f9cbb9, []int{10}
}

func (m *BackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfo.Unmarshal(m, b)
}
func (m *BackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfo.Marshal(b, m, deterministic)
}
func (m *BackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfo.Merge(m, src)
}
func (m *BackupInfo) XXX_Size() int {
	return xxx_messageInfo_BackupInfo.Size(m)
}
func (m *BackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfo proto.InternalMessageInfo

func (m *BackupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackupInfo) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *BackupInfo) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *BackupInfo) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *BackupInfo) GetTabletAlias() *topodata.TabletAlias {
	if m != nil {
		return m.TabletAlias
	}
	return nil
}

func (m *BackupInfo) GetTime() *vttime.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BackupInfo) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *BackupInfo) GetStatus() BackupInfo_Status {
	if m != nil {
		return m.Status
	}
	return BackupInfo_UNKNOWN
}

func init() {
	proto.RegisterEnum("mysqlctl.BackupInfo_Status", BackupInfo_Status_name, BackupInfo_Status_value)
	proto.RegisterType((*StartRequest)(nil), "mysqlctl.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "mysqlctl.StartResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "mysqlctl.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "mysqlctl.ShutdownResponse")
	proto.RegisterType((*RunMysqlUpgradeRequest)(nil), "mysqlctl.RunMysqlUpgradeRequest")
	proto.RegisterType((*RunMysqlUpgradeResponse)(nil), "mysqlctl.RunMysqlUpgradeResponse")
	proto.RegisterType((*ReinitConfigRequest)(nil), "mysqlctl.ReinitConfigRequest")
	proto.RegisterType((*ReinitConfigResponse)(nil), "mysqlctl.ReinitConfigResponse")
	proto.RegisterType((*RefreshConfigRequest)(nil), "mysqlctl.RefreshConfigRequest")
	proto.RegisterType((*RefreshConfigResponse)(nil), "mysqlctl.RefreshConfigResponse")
	proto.RegisterType((*BackupInfo)(nil), "mysqlctl.BackupInfo")
}

func init() { proto.RegisterFile("mysqlctl.proto", fileDescriptor_cd8c110e42f9cbb9) }

var fileDescriptor_cd8c110e42f9cbb9 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcb, 0x6e, 0xda, 0x4a,
	0x18, 0x8e, 0xc3, 0x25, 0xe6, 0xc7, 0x01, 0x34, 0x27, 0x80, 0xe3, 0xd3, 0x36, 0xae, 0xa5, 0xb6,
	0xac, 0x6c, 0x89, 0x6c, 0xda, 0xee, 0x08, 0x4d, 0x25, 0x94, 0x04, 0x2a, 0x43, 0xda, 0xaa, 0x1b,
	0x34, 0xc1, 0x83, 0xb1, 0x02, 0x1e, 0xc7, 0x33, 0x10, 0xf1, 0x0a, 0x7d, 0xd0, 0x3e, 0x47, 0xc5,
	0xf8, 0x06, 0x21, 0xe9, 0x6e, 0xbe, 0x6b, 0x62, 0xfd, 0x9f, 0x80, 0xca, 0x62, 0xcd, 0x1e, 0xe6,
	0x13, 0x3e, 0x37, 0x83, 0x90, 0x72, 0x8a, 0xe4, 0x04, 0x6b, 0x15, 0x4e, 0x03, 0xea, 0x60, 0x8e,
	0x23, 0x45, 0x53, 0x56, 0x9c, 0x7b, 0x0b, 0x12, 0x21, 0xc3, 0x02, 0x65, 0xc8, 0x71, 0xc8, 0x6d,
	0xf2, 0xb0, 0x24, 0x8c, 0xa3, 0x33, 0x28, 0x8b, 0xa4, 0x33, 0xc6, 0xa1, 0xcb, 0x54, 0x49, 0xcf,
	0xb5, 0x4a, 0x36, 0x44, 0x54, 0x27, 0x74, 0x99, 0x51, 0x85, 0xe3, 0x38, 0xc0, 0x02, 0xea, 0x33,
	0x62, 0x7c, 0x82, 0xea, 0x70, 0xb6, 0xe4, 0x0e, 0x7d, 0xf4, 0x93, 0x92, 0xf7, 0x50, 0x7d, 0xc4,
	0x1e, 0x1f, 0x4f, 0x69, 0x38, 0x8e, 0xa2, 0xaa, 0xa4, 0x4b, 0x2d, 0xd9, 0x3e, 0xde, 0xd0, 0x5f,
	0x69, 0x78, 0x23, 0x48, 0x03, 0x41, 0x2d, 0x8b, 0xc6, 0x75, 0x2a, 0x34, 0xec, 0xa5, 0x2f, 0x0c,
	0xb7, 0x81, 0x1b, 0x62, 0x87, 0xc4, 0xad, 0xc6, 0x29, 0x34, 0xf7, 0x94, 0x38, 0x54, 0x87, 0xff,
	0x6c, 0xe2, 0xf9, 0x1e, 0xef, 0x52, 0x7f, 0xea, 0xb9, 0x49, 0xa2, 0x01, 0x27, 0xbb, 0x74, 0x6c,
	0x17, 0xfc, 0x34, 0x24, 0x6c, 0xb6, 0xeb, 0x6f, 0x42, 0xfd, 0x09, 0x1f, 0x07, 0xfe, 0x1c, 0x02,
	0x5c, 0xe0, 0xc9, 0xfd, 0x32, 0xe8, 0xf9, 0x53, 0x8a, 0x10, 0xe4, 0x7d, 0xbc, 0x20, 0xe2, 0xa3,
	0x4a, 0xb6, 0x78, 0xa3, 0x57, 0x50, 0x72, 0xbc, 0x90, 0x4c, 0x38, 0x0d, 0xd7, 0xea, 0xa1, 0x10,
	0x32, 0x02, 0x69, 0x20, 0xdf, 0x93, 0x35, 0x0b, 0xf0, 0x84, 0xa8, 0x39, 0x21, 0xa6, 0x18, 0x9d,
	0x40, 0x81, 0xcd, 0x70, 0xe8, 0xa8, 0x79, 0x21, 0x44, 0x00, 0x7d, 0x04, 0x85, 0xe3, 0xbb, 0x39,
	0xe1, 0x63, 0x3c, 0xf7, 0x30, 0x53, 0x0b, 0xba, 0xd4, 0x2a, 0xb7, 0xeb, 0x66, 0x7a, 0xcd, 0x91,
	0x50, 0x3b, 0x1b, 0xd1, 0x2e, 0xf3, 0x0c, 0x20, 0x1d, 0xf2, 0x9b, 0x03, 0xab, 0x45, 0x91, 0x50,
	0xcc, 0xf8, 0xde, 0x23, 0x6f, 0x41, 0x6c, 0xa1, 0xa0, 0x06, 0x14, 0x89, 0xef, 0x7a, 0x3e, 0x51,
	0x8f, 0xc4, 0x9f, 0x8c, 0x11, 0x3a, 0x87, 0x22, 0xe3, 0x98, 0x2f, 0x99, 0x2a, 0xeb, 0x52, 0xab,
	0xd2, 0xfe, 0xdf, 0x4c, 0x57, 0x95, 0x7d, 0xbd, 0x39, 0x14, 0x16, 0x3b, 0xb6, 0x1a, 0x57, 0x50,
	0x8c, 0x18, 0x54, 0x86, 0xa3, 0xdb, 0xfe, 0x55, 0x7f, 0xf0, 0xa3, 0x5f, 0x3b, 0x40, 0x15, 0x80,
	0x5e, 0xbf, 0x3b, 0xb8, 0xf9, 0x76, 0x7d, 0x39, 0xba, 0xac, 0x49, 0x48, 0x01, 0x39, 0x45, 0x87,
	0x1b, 0x6b, 0xaf, 0xff, 0xbd, 0x73, 0xdd, 0xfb, 0x52, 0xcb, 0xa1, 0x12, 0x14, 0xa2, 0x67, 0xbe,
	0xfd, 0x3b, 0x07, 0xb2, 0xb8, 0x70, 0x97, 0xcf, 0xd1, 0x67, 0x28, 0x88, 0xa9, 0xa1, 0x46, 0xf6,
	0x7f, 0x6c, 0x8f, 0x55, 0x6b, 0xee, 0xf1, 0xf1, 0xbd, 0x0e, 0x50, 0x17, 0xe4, 0x64, 0x5a, 0xe8,
	0x74, 0xcb, 0xb6, 0xbb, 0x54, 0x4d, 0x7b, 0x4e, 0x4a, 0x4b, 0x7e, 0x42, 0xf5, 0xc9, 0xe2, 0x90,
	0x9e, 0x05, 0x9e, 0x9f, 0xa9, 0xf6, 0xf6, 0x1f, 0x8e, 0xb4, 0x79, 0x00, 0xca, 0xf6, 0x32, 0xd1,
	0xeb, 0xad, 0xd0, 0xfe, 0x90, 0xb5, 0x37, 0x2f, 0xc9, 0x69, 0xa1, 0x0d, 0xc7, 0x3b, 0xd3, 0x45,
	0x3b, 0x91, 0xfd, 0xad, 0x6b, 0x67, 0x2f, 0xea, 0x49, 0xe7, 0xc5, 0x87, 0x5f, 0xef, 0x56, 0x1e,
	0x27, 0x8c, 0x99, 0x1e, 0xb5, 0xa2, 0x97, 0xe5, 0x52, 0x6b, 0xc5, 0x2d, 0xf1, 0xdb, 0x61, 0x25,
	0x05, 0x77, 0x45, 0x81, 0xcf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xfa, 0x73, 0x30, 0x85,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MysqlCtlClient is the client API for MysqlCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MysqlCtlClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	RunMysqlUpgrade(ctx context.Context, in *RunMysqlUpgradeRequest, opts ...grpc.CallOption) (*RunMysqlUpgradeResponse, error)
	ReinitConfig(ctx context.Context, in *ReinitConfigRequest, opts ...grpc.CallOption) (*ReinitConfigResponse, error)
	RefreshConfig(ctx context.Context, in *RefreshConfigRequest, opts ...grpc.CallOption) (*RefreshConfigResponse, error)
}

type mysqlCtlClient struct {
	cc *grpc.ClientConn
}

func NewMysqlCtlClient(cc *grpc.ClientConn) MysqlCtlClient {
	return &mysqlCtlClient{cc}
}

func (c *mysqlCtlClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/mysqlctl.MysqlCtl/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlCtlClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/mysqlctl.MysqlCtl/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlCtlClient) RunMysqlUpgrade(ctx context.Context, in *RunMysqlUpgradeRequest, opts ...grpc.CallOption) (*RunMysqlUpgradeResponse, error) {
	out := new(RunMysqlUpgradeResponse)
	err := c.cc.Invoke(ctx, "/mysqlctl.MysqlCtl/RunMysqlUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlCtlClient) ReinitConfig(ctx context.Context, in *ReinitConfigRequest, opts ...grpc.CallOption) (*ReinitConfigResponse, error) {
	out := new(ReinitConfigResponse)
	err := c.cc.Invoke(ctx, "/mysqlctl.MysqlCtl/ReinitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlCtlClient) RefreshConfig(ctx context.Context, in *RefreshConfigRequest, opts ...grpc.CallOption) (*RefreshConfigResponse, error) {
	out := new(RefreshConfigResponse)
	err := c.cc.Invoke(ctx, "/mysqlctl.MysqlCtl/RefreshConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MysqlCtlServer is the server API for MysqlCtl service.
type MysqlCtlServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	RunMysqlUpgrade(context.Context, *RunMysqlUpgradeRequest) (*RunMysqlUpgradeResponse, error)
	ReinitConfig(context.Context, *ReinitConfigRequest) (*ReinitConfigResponse, error)
	RefreshConfig(context.Context, *RefreshConfigRequest) (*RefreshConfigResponse, error)
}

// UnimplementedMysqlCtlServer can be embedded to have forward compatible implementations.
type UnimplementedMysqlCtlServer struct {
}

func (*UnimplementedMysqlCtlServer) Start(ctx context.Context, req *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedMysqlCtlServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (*UnimplementedMysqlCtlServer) RunMysqlUpgrade(ctx context.Context, req *RunMysqlUpgradeRequest) (*RunMysqlUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunMysqlUpgrade not implemented")
}
func (*UnimplementedMysqlCtlServer) ReinitConfig(ctx context.Context, req *ReinitConfigRequest) (*ReinitConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReinitConfig not implemented")
}
func (*UnimplementedMysqlCtlServer) RefreshConfig(ctx context.Context, req *RefreshConfigRequest) (*RefreshConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshConfig not implemented")
}

func RegisterMysqlCtlServer(s *grpc.Server, srv MysqlCtlServer) {
	s.RegisterService(&_MysqlCtl_serviceDesc, srv)
}

func _MysqlCtl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlCtlServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysqlctl.MysqlCtl/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlCtlServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MysqlCtl_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlCtlServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysqlctl.MysqlCtl/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlCtlServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MysqlCtl_RunMysqlUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunMysqlUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlCtlServer).RunMysqlUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysqlctl.MysqlCtl/RunMysqlUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlCtlServer).RunMysqlUpgrade(ctx, req.(*RunMysqlUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MysqlCtl_ReinitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReinitConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlCtlServer).ReinitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysqlctl.MysqlCtl/ReinitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlCtlServer).ReinitConfig(ctx, req.(*ReinitConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MysqlCtl_RefreshConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlCtlServer).RefreshConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysqlctl.MysqlCtl/RefreshConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlCtlServer).RefreshConfig(ctx, req.(*RefreshConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MysqlCtl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mysqlctl.MysqlCtl",
	HandlerType: (*MysqlCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _MysqlCtl_Start_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _MysqlCtl_Shutdown_Handler,
		},
		{
			MethodName: "RunMysqlUpgrade",
			Handler:    _MysqlCtl_RunMysqlUpgrade_Handler,
		},
		{
			MethodName: "ReinitConfig",
			Handler:    _MysqlCtl_ReinitConfig_Handler,
		},
		{
			MethodName: "RefreshConfig",
			Handler:    _MysqlCtl_RefreshConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mysqlctl.proto",
}
